# This file is generated by IceVault release automation. DO NOT EDIT.
cask "icevault" do
  arch arm: "arm64", intel: "x86_64"

  version "0.1.18"
  sha256 arm: "dfdf33606d2faf82c136c7ca27b79f0e1ebdcd131687c81ca226e9e7e9db36d3", intel: "4711d1c73f1b418af684cac82f1b27b0ced7c375a962c995aee13527b8336b97"

  url "https://github.com/lydakis/icevault/releases/download/v#{version}/IceVault-#{version}-macos-#{arch}.dmg"
  name "IceVault"
  desc "Automated cold backups to AWS S3 Glacier Deep Archive"
  homepage "https://github.com/lydakis/icevault"

  depends_on macos: ">= :sonoma"

  app "IceVault.app"

  livecheck do
    url :url
    strategy :github_latest
  end
end
