# This file is generated by IceVault release automation. DO NOT EDIT.
cask "icevault" do
  arch arm: "arm64", intel: "x86_64"

  version "0.1.15"
  sha256 arm: "127e9d86737c26698b3d3fc0e826765a187087f53e6f37ab870fd16d97cc94f7", intel: "d3b50745258d1831953bdd692451903f2b8e2ac800a563de11b7fc907ed9b065"

  url "https://github.com/lydakis/icevault/releases/download/v#{version}/IceVault-#{version}-macos-#{arch}.dmg"
  name "IceVault"
  desc "Automated cold backups to AWS S3 Glacier Deep Archive"
  homepage "https://github.com/lydakis/icevault"

  depends_on macos: ">= :sonoma"

  app "IceVault.app"

  livecheck do
    url :url
    strategy :github_latest
  end
end
