# This file is generated by IceVault release automation. DO NOT EDIT.
cask "icevault" do
  arch arm: "arm64", intel: "x86_64"

  version "0.0.0"
  sha256 arm: "0000000000000000000000000000000000000000000000000000000000000000", intel: "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/lydakis/icevault/releases/download/v#{version}/IceVault-#{version}-macos-#{arch}.dmg"
  name "IceVault"
  desc "Automated cold backups to AWS S3 Glacier Deep Archive"
  homepage "https://github.com/lydakis/icevault"

  app "IceVault.app"

  livecheck do
    url :url
    strategy :github_latest
  end
end
